### ISSUE TITLE
KT - scanBasePackages Usages R&D 

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#10]
Explain the usages of scanBasePackages 

Provide class file where does it implemented 

Provide reference link

**Comment by AdibahTalib** [comment]
To do the dependency injection the packages must be scanned for necessary beans.

scanBasePackages allows us to provide a wildcard to our package name so that any sub-packages will also be scanned

https://codetinkering.com/spring-boot-package-scanning-configuration/

**Comment by Devarajan222** [comment]
Base packages to scan for annotated components.

scanBasePackageClasses
Type-safe alternative to scanBasePackages() for specifying the packages to scan for annotated components.

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/SpringBootApplication.html#scanBasePackages--
