### ISSUE TITLE
@RestController vs @Service R&D

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#12]
Research and Development above the subject above 

Provide the reference link below.

**Comment by AdibahTalib** [comment]
- Spring @Service Annotations is a stereotype for the service layer and also a specialization of @Component annotation. Spring Service Annotations can only be used for classes. It is used to indicate a class as a service provider.

- The @RestController annotation in Spring MVC is to simplify the creation of RESTful web services which returns the object and the object data is written directly to the http response as json or xml. 
- The @RestController annotation is a combination of the @Controller and the @ResponseBody annotation which it eliminates the need to annotate every request handling method of the controller class with the @ResponseBody annotation

References:
1. https://www.journaldev.com/21435/spring-service-annotation#:~:text=Spring%20%40Service%20annotation%20is%20a,class%20as%20a%20service%20provider.

2. https://www.baeldung.com/spring-controller-vs-restcontroller
