### ISSUE TITLE
KT - 4 Basic Java Fundamental 

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#16]
Describe each of the below 

Abstraction, Inheritance, Polymorphism and Encapsulation.

**Comment by haziramazlan** [comment]
### Abstraction:
- A concept aiming to overcome large codebase where objects communicate with each other a lot.
- Each object should only expose a high-level mechanism for using it, in which this mechanism should hide internal implementation details and only reveal operations that are relevant for the other objects.
- It is like a small set of public methods where other class can call without “knowing” how they work.
![image](https://user-images.githubusercontent.com/80657245/113012679-9039aa00-91ad-11eb-9092-2d7c5c2209ba.png)


### Inheritance:
- To reuse common variables and extract unique variable into a separate class.
- Form hierarchy by creating parent class and child class.
- Child class can access all private variables and methods from parent class, and can also have their own variables and methods.
![image](https://user-images.githubusercontent.com/80657245/113012880-c0814880-91ad-11eb-80fe-483d8d1929a3.png)


### Polymorphism:
- Provides a way to use a class exactly like its parent class so there will be no confusion with mixing types.
- A parent class outlines a bunch of common methods, then each child class implements its own version of these methods.
![image](https://user-images.githubusercontent.com/80657245/113012925-cf67fb00-91ad-11eb-82fe-f71d27d18977.png)


### Encapsulation:
- A binding between private state and public methods.
- When each object inside a class keeps its state private, other objects don’t have direct access to this state. Instead, they can only call a list of public methods.
- Other classes cannot use the private objects. They can use the methods provided, but cannot change the state.
![image](https://user-images.githubusercontent.com/80657245/113013082-faeae580-91ad-11eb-9ab7-3781ab03f8bc.png)


**References**:
1. https://www.indeed.com/career-advice/career-development/what-is-object-oriented-programming 
2. https://www.freecodecamp.org/news/object-oriented-programming-concepts-21bb035f7260/
