### ISSUE TITLE
KT-Query using PARTITION BY

### ISSUE THREAD

**Issue by nadizeq** [pcyuen98/covidAngular#18]

**Comment by nadizeq** [comment]
The function of PARTITION BY clause is to divide the result set into partitions and perform computation on each subset of partitioned data. 

The syntax of PARTITION BY clause:
window_function ( expression ) OVER (
    PARTITION BY expression1, expression2, ...
    order_clause
    frame_clause
)

An example of it which returns the employee's salary and the average salary of the employee department:
SELECT 
    first_name,
    last_name,
    department_id, 
    ROUND(AVG(salary) OVER (
        PARTITION BY department_id
    )) avg_department_salary
FROM
    employees;

Resource: 
1. https://www.sqltutorial.org/sql-window-functions/sql-partition-by/

**Comment by pcyuen98** [comment]
If return of the sql needs to be customize as per example above. Then it needs a customized bean or solution as below

https://stackoverflow.com/questions/33701905/springdatajpa-custom-data-mapping-with-native-query
