### ISSUE TITLE
CORS Error during HTTP Request from Angular but it's working from Chrome

### ISSUE THREAD

**Issue by Devarajan222** [pcyuen98/covidAngular#3]

**Comment by haziramazlan** [comment]
<img width="195" alt="Screenshot 2021-03-25 at 11 30 31 AM" src="https://user-images.githubusercontent.com/80657245/112415085-27da6b00-8d5e-11eb-9583-fae21b28b303.png">

try to change folder name to 'com.app.config'

**Comment by Devarajan222** [comment]
![12](https://user-images.githubusercontent.com/80657203/112416751-44c46d80-8d61-11eb-9df4-8ac8d90000b4.PNG)

**Comment by Devarajan222** [comment]
Its not working , still shows the error

**Comment by haziramazlan** [comment]
![image](https://user-images.githubusercontent.com/80657245/112417015-ba303e00-8d61-11eb-9a1a-66d13ab8984e.png)
in StartCovidApplication.java you have this "com.app.config" but your folder name is app.com.config.

for mapper error, need to run maven build for my-covid-model then restart the app

**Comment by pcyuen98** [comment]
@haziramazlan this can be closed. Please update your link and score too here ya on group exercise tab.
https://docs.google.com/spreadsheets/d/1KtmEnBNoG6VCbFY-vwyTTwWD8x9hgqIG/edit#gid=8489761

**Comment by haziramazlan** [comment]
noted, sir
