### ISSUE TITLE
What is DevOps

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#31]
Do a research as per title above and provide reference link.

**Comment by abdrhm293** [comment]
DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). It aims to shorten the systems development life cycle and provide continuous delivery with high software quality.[1] DevOps is complementary with Agile software development; several DevOps aspects came from the Agile methodology.
[https://en.wikipedia.org/wiki/DevOps](url)
