### ISSUE TITLE
SpringBoot Dependency Injection

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#32]
Research as per title above and provide reference link

**Comment by abdrhm293** [comment]
Dependency Injection is a fundamental aspect of the Spring framework, through which the Spring container “injects” objects into other objects or “dependencies”. Simply put, this allows for loose coupling of components and moves the responsibility of managing components onto the container.
[https://www.baeldung.com/spring-dependency-injection](url)
