### ISSUE TITLE
Spring Boot Configuration

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#33]
Research as per topic above and provide reference link. It should contain the 2 annotation and services as below

@EnableAutoConfiguration
@ComponentScan

**Comment by abdrhm293** [comment]
In Spring Boot, we can use Spring Framework to define our beans and their dependency injection. The @ComponentScan annotation is used to find beans and the corresponding injected with @Autowired annotation. If you followed the Spring Boot typical layout, no need to specify any arguments for @ComponentScan annotation.
[https://www.tutorialspoint.com/spring_boot/spring_boot_beans_and_dependency_injection.htm](url)

The @EnableAutoConfiguration annotation enables Spring Boot to auto-configure the application context. Therefore, it automatically creates and registers beans based on both the included jar files in the classpath and the beans defined by us.
[https://www.baeldung.com/spring-componentscan-vs-enableautoconfiguration](url)
