### ISSUE TITLE
KT - Angular Practical 2

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#4]

**Comment by uyunAkmal** [comment]
Need explanation on how to do the practical no 2

**Comment by AdibahTalib** [comment]
1. go to http://localhost:4200/hello
2. right click on the page and click inspect
3. click Network -> choose hello -> go to Headers

![Capture](https://user-images.githubusercontent.com/80657296/112429343-7c3e1480-8d77-11eb-9dfd-99bf722db128.PNG)
