### ISSUE TITLE
KT - Angular Practical (warning in console)

### ISSUE THREAD

**Issue by pcyuen98** [pcyuen98/covidAngular#5]
Peer review of the practical 6 and 7

**Comment by pcyuen98** [comment]
@nadizeq Just check with Deva whether he understands on this part?

**Comment by nadizeq** [comment]
When opening Angular on web browser, there are warnings that are shown in the console in the tab where it states that the usage of "id" is not unique. 

To curb this problem, change the value that is assigned to the "id" to have different name and once it saved, the warning will not show in the console after inspecting it.
